# Generated by Django 5.0.3 on 2024-03-21 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["title"]},
        ),
    ]
