# Generated by Django 5.0.3 on 2024-03-21 10:21

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_alter_quiz_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="quiz_id",
            field=models.CharField(
                default=quiz.models.generate_id, editable=False, max_length=10
            ),
        ),
    ]
