# Generated by Django 5.0.3 on 2024-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_question_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="related_options",
            field=models.ManyToManyField(blank=True, to="quiz.option"),
        ),
    ]
