# Generated by Django 5.0.3 on 2024-03-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_quiz_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
